<?php

namespace Deg540\PHPTestingBoilerplate\Test;

use PHPUnit\Framework\TestCase;

class FizzbuzzTest  extends TestCase
{

    private fizzbuzz $fizzbuzz;
    /**
     * @setup
     */
    protected function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub
        $this->fizzbuzz = new fizzbuzz(); //Asi lo declaramos fuera de los test para no declarar lo mismo en cada test
    }

    /**
     * @test
     */
    public function when_1_given_return_1()
    {
        $convertedValue = $this->fizzbuzz->convert(1);

        $this->assertEquals("1", $convertedValue);
    }
    /**
     * @test
     */
    public function when_3_given_return_fizz()
    {
        $convertedValue = $this->fizzbuzz->convert(3);

        $this->assertEquals("fizz", $convertedValue);
    }

    /**
     * @test
     */
    public function when_5_given_return_buzz()
    {
        $convertedValue = $this->fizzbuzz->convert(5);

        $this->assertEquals("buzz", $convertedValue);
    }
    /**
     * @test
     */
    public function when_15_given_return_fizzbuzz()
    {
        $convertedValue = $this->fizzbuzz->convert(15);

        $this->assertEquals("fizzbuzz", $convertedValue);
    }
    /**
     * @test
     */
    public function when_17_given_return_17()
    {
        $convertedValue = $this->fizzbuzz->convert(17);

        $this->assertEquals("17", $convertedValue);
    }
    /**
     * @test
     */
    public function when_35_given_return_fizzbuzz()
    {
        $convertedValue = $this->fizzbuzz->convert(35);

        $this->assertEquals("fizzbuzz", $convertedValue);
    }

}